language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t ladis/docker-react -f Dockerfile.dev .

script:
  - docker run ladis/docker-react npm run test -- --coverages