sudo: required
services:
  - docker

language: node_js

node_js:
- "8"

before_install:
  - docker build -t ladis/docker-react -f Dockerfile.dev .

script:
  - docker run ladis/docker-react npm run test -- --coverages